config/routes.rb
Sepol::Application.routes.draw do

  Mercury::Engine.routes

  resources :equipaments

  resources :reserves

  resources :equipaments do
    resources :reserves
  end

  root :to => 'homes#index'

  devise_for :users

  resources :publications

  resources :researchers

  resources :pesquisadores

  resources :homes do
    member do
      put :mercury_update
    end
  end

end

app/models/publication.rb
class Publication < ActiveRecord::Base
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
    before_filter :authenticate_user!, :except => [:show, :index]
  # GET /publications
  # GET /publications.json
  def index
    @publications = Publication.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @publications }
    end
  end

  # GET /publications/1
  # GET /publications/1.json
  def show
    @publication = Publication.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @publication }
    end
  end

  # GET /publications/new
  # GET /publications/new.json
  def new
    @publication = Publication.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @publication }
    end
  end

  # GET /publications/1/edit
  def edit
    @publication = Publication.find(params[:id])
  end

  # POST /publications
  # POST /publications.json
  def create
    @publication = Publication.new(params[:publication])

    respond_to do |format|
      if @publication.save
        format.html { redirect_to @publication, notice: 'Publication was successfully created.' }
        format.json { render json: @publication, status: :created, location: @publication }
      else
        format.html { render action: "new" }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /publications/1
  # PUT /publications/1.json
  def update
    @publication = Publication.find(params[:id])

    respond_to do |format|
      if @publication.update_attributes(params[:publication])
        format.html { redirect_to @publication, notice: 'Publication was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1
  # DELETE /publications/1.json
  def destroy
    @publication = Publication.find(params[:id])
    @publication.destroy

    respond_to do |format|
      format.html { redirect_to publications_url }
      format.json { head :ok }
    end
  end
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/publications/_form.html.erb
<%= form_for(@publication) do |f| %>
  <% if @publication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

      <ul>
      <% @publication.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" >
    <%= f.label :titulo %><br />
    <%= f.text_area :titulo, :rows=>1 %>
  </div>
  <div class="field">
    <%= f.label :abstract %><br />
    <%= f.text_area :abstract, :rows => 10 %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.url_field :link %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/publications/edit.html.erb
<h1>Editar Publicação</h1>

<%= render 'form' %>

<div class="btn">
<%= link_to 'Mostrar', @publication %>
</div>
<div class="btn">
<%= link_to 'Voltar', publications_path %>
</div>

app/views/publications/index.html.erb
<h1>Publicações</h1>

<table class="zebra-striped">
  <tr>
    <th>Titulo</th>
    <th>Abstract</th>
    <th>Link</th>
    <th></th>
    <th></th>
  </tr>

<% @publications.each do |publication| %>
  <tr>
    <td><%= publication.titulo %></td>
    <td><%= publication.abstract[0..60] + '...' %> <br /><%=link_to 'Ler Mais', publication %></td>
    <td><a href="<%=publication.link %>"> <%=publication.link[0..30] + "..."%></a></td>
    <% if user_signed_in? %>
      <td class="btn"><%= link_to 'Editar', edit_publication_path(publication)%></td>
      <td class="btn"><%= (link_to 'Apagar', publication, confirm: 'Esta ação irá excluir a publicação!', method: :delete)%></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />
<% if user_signed_in? %>
  <div class="btn">
    <%= link_to 'Adicionar Publicação', new_publication_path %>
  </div>
<%end %>

app/views/publications/new.html.erb
<h1>Adicionar Publicação</h1>

<%= render 'form' %>
<div class="btn">
<%= link_to 'Voltar', publications_path %>
</div>

app/views/publications/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  <%= @publication.titulo %>
</h2>

<p>
  <%= @publication.abstract %>
</p>

<p>
  <b>Link:</b>
  <a href="<%=@publication.link %>"> <%=@publication.link%></a>
</p>

<div class="btn">
  <%= link_to 'Editar', edit_publication_path(@publication) if user_signed_in? %>
</div>

<div class="btn">
  <%= link_to 'Voltar', publications_path %>
</div>