config/routes.rb
Sepol::Application.routes.draw do

  Mercury::Engine.routes

  resources :equipaments

  resources :reserves

  resources :equipaments do
    resources :reserves
  end

  root :to => 'homes#index'

  devise_for :users

  resources :publications

  resources :researchers

  resources :pesquisadores

  resources :homes do
    member do
      put :mercury_update
    end
  end

end

app/models/equipament.rb
class Equipament < ActiveRecord::Base
  validates_presence_of :nome, :descricao
  has_many :reserves

  has_attached_file :picture, :styles => {:small => "150x150>", :large => "650x550>"},
                               :url  => "/pictures/equipaments/:id/:style/:basename.:extension",
                               :path => ":rails_root/public/pictures/equipaments/:id/:style/:basename.:extension"

  validates_attachment_presence :picture
  validates_attachment_content_type :picture, :content_type => ['image/jpeg', 'image/png']
end

app/controllers/equipaments_controller.rb
class EquipamentsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]

  # GET /equipaments
  # GET /equipaments.json
  def index
    @equipaments = Equipament.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @equipaments }
    end
  end

  # GET /equipaments/1
  # GET /equipaments/1.json
  def show
    @equipament = Equipament.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @equipament }
    end
  end

  # GET /equipaments/new
  # GET /equipaments/new.json
  def new
    @equipament = Equipament.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @equipament }
    end
  end

  # GET /equipaments/1/edit
  def edit
    @equipament = Equipament.find(params[:id])
  end

  # POST /equipaments
  # POST /equipaments.json
  def create
    @equipament = Equipament.new(params[:equipament])

    respond_to do |format|
      if @equipament.save
        format.html { redirect_to @equipament, notice: 'Equipamento adicionado com sucesso.' }
        format.json { render json: @equipament, status: :created, location: @equipament }
      else
        format.html { render action: "new" }
        format.json { render json: @equipament.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /equipaments/1
  # PUT /equipaments/1.json
  def update
    @equipament = Equipament.find(params[:id])

    respond_to do |format|
      if @equipament.update_attributes(params[:equipament])
        format.html { redirect_to @equipament, notice: 'Equipamento atualizado com sucesso.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @equipament.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /equipaments/1
  # DELETE /equipaments/1.json
  def destroy
    @equipament = Equipament.find(params[:id])
    @equipament.destroy

    respond_to do |format|
      format.html { redirect_to equipaments_url }
      format.json { head :ok }
    end
  end
end

app/helpers/equipaments_helper.rb
module EquipamentsHelper
end

app/views/equipaments/_form.html.erb
<%= form_for(@equipament) do |f| %>
  <% if @equipament.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@equipament.errors.count, "error") %> prohibited this equipament from being saved:</h2>

      <ul>
      <% @equipament.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br />
    <%= f.text_area :descricao %>
  </div>
  <div class="field">
    <%= f.label :picture %><br />
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/equipaments/edit.html.erb
<h1>Editar equipamento</h1>

<%= render 'form' %>

<div class="btn">
  <%= link_to 'Mostrar', @equipament %> |
</div>

<div class="btn">
  <%= link_to 'Voltar', equipaments_path %>
</div>

app/views/equipaments/index.html.erb
<h2>Equipamentos</h2><hr>

<% if user_signed_in? %>

  <table class = "zebra-striped">
    <tr>
      <th>nome</th>
      <th>descricao</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

  <% @equipaments.each do |equipament| %>
    <tr>
      <td><%= equipament.nome %></td>
      <td><%= equipament.descricao %></td>
      <td class="btn" ><%= link_to 'Mostrar', equipament %></td>
      <td> </td>
      <td class="btn"><%= link_to 'Editar', edit_equipament_path(equipament)%></td>
      <td> </td>
      <td class="btn">
        <%= (link_to 'Apagar', equipament, confirm: 'Essa ação irá apagar o equipamento!', method: :delete)%>
      </td>
    </tr>
  <% end %>
  </table>
  <div class="btn">
    <%= link_to 'Adicionar Equipamento', new_equipament_path%>
  </div>
<% else %>
  <% elementos_por_linha = 4%>

  <% @equipaments.in_groups_of(elementos_por_linha,0) do |grupos| %>
  <ul class="media-grid">
    <li>
      <% elementos_por_linha.times do |equipament| %>
        <% if grupos[equipament].class != Equipament %>
        <%else%>
          <a href="<%= grupos[equipament].picture(:large)%>" rel="lightbox" title="<%= grupos[equipament].descricao%>">
          <img src="<%= grupos[equipament].picture.url(:small)%>"  width="100" height="100" alt="" />
        <%end%>
      <% end %>
      </a>
    </li>
  </ul>

  <% end %>
<% end %>

app/views/equipaments/new.html.erb
<h1>Adicionar Equipamento</h1>

<%= render 'form' %>
<div class="btn">
  <%= link_to 'Voltar', equipaments_path %>
</div>

app/views/equipaments/show.html.erb
<p>
  <b>Nome:</b>
  <%= @equipament.nome %>
</p>

<ul class="media-grid">
  <li>
    <a>
      <%= image_tag @equipament.picture(:large) %>
    </a>
  </li>
</ul>

<p>
  <b>Descricao:</b>
  <%= @equipament.descricao %>
</p>

<br/>
<div class="btn">
  <%= link_to 'Editar', edit_equipament_path(@equipament) if user_signed_in? %>
</div>
<div class="btn">
  <%= link_to 'Apagar', @equipament, confirm: 'Essa ação irá apagar o equipamento!', method: :delete%>
</div>
<div class="btn">
  <%= link_to 'Voltar', equipaments_path %>
</div>