config/routes.rb
Sepol::Application.routes.draw do

  Mercury::Engine.routes

  resources :equipaments

  resources :reserves

  resources :equipaments do
    resources :reserves
  end

  root :to => 'homes#index'

  devise_for :users

  resources :publications

  resources :researchers

  resources :pesquisadores

  resources :homes do
    member do
      put :mercury_update
    end
  end

end

app/models/researcher.rb
class Researcher < ActiveRecord::Base
  validates_presence_of :nome
  has_attached_file :avatar,  :default_url => "/avatares/researchers/default/:style/default.png",
                               :styles => {:small => "300x300>", :thumb => "100x100"},
                               :url  => "/avatares/researchers/:id/:style/:basename.:extension",
                               :path => ":rails_root/public/avatares/researchers/:id/:style/:basename.:extension"

  validates_attachment_content_type :avatar, :content_type => ['image/jpeg', 'image/png']
end

app/controllers/researchers_controller.rb
class ResearchersController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]
  # GET /researchers
  # GET /researchers.json
  def index
    @researchers = Researcher.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @researchers }
    end
  end

  # GET /researchers/1
  # GET /researchers/1.json
  def show
    @researcher = Researcher.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @researcher }
    end
  end

  # GET /researchers/new
  # GET /researchers/new.json
  def new
    @researcher = Researcher.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @researcher }
    end
  end

  # GET /researchers/1/edit
  def edit
    @researcher = Researcher.find(params[:id])
  end

  # POST /researchers
  # POST /researchers.json
  def create
    @researcher = Researcher.new(params[:researcher])

    respond_to do |format|
      if @researcher.save
        format.html { redirect_to @researcher, notice: 'Researcher was successfully created.' }
        format.json { render json: @researcher, status: :created, location: @researcher }
      else
        format.html { render action: "new" }
        format.json { render json: @researcher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /researchers/1
  # PUT /researchers/1.json
  def update
    @researcher = Researcher.find(params[:id])

    respond_to do |format|
      if @researcher.update_attributes(params[:researcher])
        format.html { redirect_to @researcher, notice: 'Researcher was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @researcher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /researchers/1
  # DELETE /researchers/1.json
  def destroy
    @researcher = Researcher.find(params[:id])
    @researcher.destroy

    respond_to do |format|
      format.html { redirect_to researchers_url }
      format.json { head :ok }
    end
  end
end

app/helpers/researchers_helper.rb
module ResearchersHelper
end

app/views/researchers/_form.html.erb
<%= form_for(@researcher) do |f| %>
  <% if @researcher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@researcher.errors.count, "") %> Ocorreu um erro ao adicionar o pesquisador. verifique os campos obrigatórios:</h2>

      <ul>
      <% @researcher.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome%>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :cargo %><br />
    <%=  f.select :cargo, ([["Professor", "professor"],
                            ["Bolsista de I.C.", "bolsista_i_c"],
                            ["Pós-Graduação", "pos_graduacao"] ,
                            ["Colaborador", "colaborador"],
                            ["Apoio Técnico", "apoio_tecnico"]]) %>
  </div>
  <div class="field">
    <%= f.label :lattes %><br />
    <%= f.url_field :lattes %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br />
    <%= f.file_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/researchers/edit.html.erb
<h1>Editar Pesquisador</h1>

<%= render 'form' %>
<div class="btn">
  <%= link_to 'Mostrar', @researcher %>
</div>
<div class="btn">
  <%= link_to 'Voltar', researchers_path %>
</div>

app/views/researchers/index.html.erb
<h1>Grupo de Pesquisa</h1>

<% professores, colaboradores, alunos_pos, bolsistas_ic, apoio = [],[],[],[],[]%>

<% @researchers.each do |researcher| %>
  <% professores << researcher if researcher.cargo == "professor" %>
  <% colaboradores << researcher if researcher.cargo == "colaboradores" %>
  <% alunos_pos << researcher if researcher.cargo == "pos_graduacao" %>
  <% bolsistas_ic << researcher if researcher.cargo == "bolsista_i_c" %>
  <% apoio << researcher if researcher.cargo == "apoio_tecnico" %>
<% end %>


<h3>Professores</h3>
<table  class="zebra-striped">
  <tr>
    <th></th>
    <th>Nome</th>
    <th>Email</th>
    <th>Lattes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% professores.each do |professor| %>
  <tr>
    <td>
      <ul class="media-grid">
        <li>
          <a>
            <img src="<%= professor.avatar.url(:thumb)%>"/>
          </a>
        </li>
      </ul>
    </td>
    <td>
      <%= link_to  professor.nome, researcher_path(professor)%>
    </td>
    <td><%= professor.email %></td>
    <td><a href="<%= professor.lattes %>"><%= professor.lattes %></a></td>
    <% if user_signed_in? %>
      <td class="btn"><%= link_to 'Editar', edit_researcher_path(professor)%></td>
      <td class="btn"><%= (link_to 'Apagar', professor, confirm: 'Esta ação irá excluir o professor!', method: :delete)%></td>
    <% end %>
  </tr>
<% end %>
</table>


<br/>
<br />

<h3>Colaboradores</h3>
<table  class="zebra-striped">
  <tr>
    <th></th>
    <th>Nome</th>
    <th>Email</th>
    <th>Lattes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% colaboradores.each do |colaborador| %>
  <tr>
    <td>
      <ul class="media-grid">
        <li>
          <a>
            <img src="<%= colaborador.avatar.url(:thumb)%>"/>
          </a>
        </li>
      </ul>
    </td>
    <td>
      <%= link_to  colaborador.nome, researcher_path(colaborador)%>
    </td>
    <td><%= colaborador.email %></td>
    <td><a href="<%= colaborador.lattes %>"><%= colaborador.lattes %></a></td>
    <% if user_signed_in? %>
      <td class="btn"><%= link_to 'Editar', edit_researcher_path(colaborador)%></td>
      <td class="btn"><%= (link_to 'Apagar', colaborador, confirm: 'Esta ação irá excluir o colaborador!', method: :delete)%></td>
    <% end %>
  </tr>
<% end %>
</table>

<br/>
<br/>


<h3>Alunos de Pós-Graduação</h3>
<table  class="zebra-striped">
  <tr>
    <th></th>
    <th>Nome</th>
    <th>Email</th>
    <th>Lattes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% alunos_pos.each do |aluno_pos| %>
  <tr>
    <td>
      <ul class="media-grid">
        <li>
          <a <% link_to 'Mostrar', aluno_pos %>>
            <img src="<%= aluno_pos.avatar.url(:thumb)%>"/>
          </a>
        </li>
      </ul>
    </td>
    <td>
      <%= link_to aluno_pos.nome, researcher_path(aluno_pos)%>
    </td>
    <td><a href="<%= aluno_pos.email %>"><%= aluno_pos.lattes %></a></td>
    <td><%= aluno_pos.lattes %></td>
    <% if user_signed_in? %>
      <td class="btn"><%= link_to 'Editar', edit_researcher_path(aluno_pos)%></td>
      <td class="btn"><%= (link_to 'Apagar', aluno_pos, confirm: 'Esta ação irá excluir o aluno!', method: :delete)%></td>
    <% end %>
  </tr>
<% end %>
</table>

<br/>
<br/>

<h3>Bolsistas de Iniciação Científica</h3>
<table  class="zebra-striped">
  <tr>
    <th></th>
    <th>Nome</th>
    <th>Email</th>
    <th>Lattes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% bolsistas_ic.each do |bolsista_i_c| %>
  <tr>
    <td>
      <ul class="media-grid">
        <li>
          <a <% link_to 'Mostrar', bolsista_i_c %>>
            <img src="<%= bolsista_i_c.avatar.url(:thumb)%>"/>
          </a>
        </li>
      </ul>
    </td>
    <td>
      <%= link_to  bolsista_i_c.nome, researcher_path(bolsista_i_c)%>
    </td>
    <td><%= bolsista_i_c.email %></td>
    <td><a href="<%= bolsista_i_c.lattes %>"><%= bolsista_i_c.lattes %></a></td>
    <% if user_signed_in? %>
      <td class="btn"><%= link_to 'Editar', edit_researcher_path(bolsista_i_c)%></td>
      <td class="btn"><%= (link_to 'Apagar', bolsista_i_c, confirm: 'Esta ação irá excluir o bolsista!', method: :delete)%></td>
    <% end %>
  </tr>
<% end %>
</table>


<br/>
<br />
<% if user_signed_in? %>
  <div class="btn">
    <%= link_to 'Adicionar Pesquisador', new_researcher_path%>
  </div>
<% end %>

app/views/researchers/new.html.erb
<h1>Adicionar Pesquisador</h1>

<%= render 'form' %>
<div class="btn">
<%= link_to 'Voltar', researchers_path %>
</div>

app/views/researchers/show.html.erb
<p id="notice"><%= notice %></p>

<ul class="media-grid">
  <li>
    <a>
      <img src="<%= @researcher.avatar.url(:small)%>"/>
    </a>
  </li>
</ul>

<p>
  <b>Nome:</b>
  <%= @researcher.nome %>
</p>

<p>
  <b>Email:</b>
  <%= @researcher.email %>
</p>

<p>
  <b>Cargo:</b>
  <%= @researcher.cargo %>
</p>

<p>
  <b>Lattes:</b>
  <a href="<%= @researcher.lattes %>"><%= @researcher.lattes %></a>
</p>
<%if user_signed_in?%>
<div class = "btn">
<%= link_to 'Editar', edit_researcher_path(@researcher)%>
</div>
<%end%>
<div class = "btn">
<%= link_to 'Voltar', researchers_path %>
</div>