config/routes.rb
Sepol::Application.routes.draw do

  Mercury::Engine.routes

  resources :equipaments

  resources :reserves

  resources :equipaments do
    resources :reserves
  end

  root :to => 'homes#index'

  devise_for :users

  resources :publications

  resources :researchers

  resources :pesquisadores

  resources :homes do
    member do
      put :mercury_update
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
	<title>Sepol</title>
  <%= javascript_include_tag "application" %>
  <link rel="stylesheet" href="http://twitter.github.com/bootstrap/1.4.0/bootstrap.min.css">
	<link rel="stylesheet" href="css/lightbox.css" type="text/css" media="screen" />
	<script src="js/prototype.js" type="text/javascript"></script>
	<script src="js/scriptaculous.js?load=effects,builder" type="text/javascript"></script>
	<script src="js/lightbox.js" type="text/javascript"></script>
  <%= stylesheet_link_tag    "application" %>
	<%= csrf_meta_tag %>
</head>

<body>

    <div class="topbar">
      <div class="fill">
        <div class="container">
          <a class="brand" href="#">Sepol</a>
          <ul class="nav">
            <li class="active"><a href="<%= homes_path %>">Home</a></li>
            <li><a href="<%= equipaments_path %>">Infra Estrutura</a></li>
            <li><a href="<%= researchers_path %>">Grupo de Pesquisa</a></li>
            <li><a href="<%= publications_path %>">Publicações</a></li>
            <li><a href=" http://www.uenf.br/index.php ">UENF</a></li>
            <li><a href="http://www.uenf.br/Uenf/Pages/CCT/Lamav/">Lamav</a></li>
            <li><a href="http://www.cnpq.br/">CNPq </a></li>
          </ul>
          <p  class="pull-right" style="color: #757575">
             <% if user_signed_in? %>
                olá, <%= current_user.name %>
                  ( <%= link_to "Sair", destroy_user_session_path, :action => :destroy %> )
             <% else %>
                 <%= link_to "Entrar", new_user_session_path %>
            <% end %>
          </p>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="content">
        <div class="page-header">
          <h1><small><br/>
          </small></h1>
        </div>
        <div class="row">
            <%= yield %>
        </div>
      <br/>
      <br/>
      </div>
      <footer>
        <p>
          Universidade Estadual do Norte Fluminense Darcy Ribeiro | Av. Alberto Lamego, 2000 - Parque Califórnia<br />
          Laboratório de Materiais Avançados - LAMAV | Centro de Ciência e Tecnologia – CCT <br />
          Campos dos Goytacazes - RJ | CEP: 28013-602<br /><br />
        </p>
      </footer>

    </div> <!-- /container -->
</body>

app/views/layouts/mercury.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, maximum-scale=1.0, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <title>Mercury Editor</title>
    <%= stylesheet_link_tag    'mercury', 'mercury_overrides' %>
    <%= javascript_include_tag 'mercury' %>
  </head>
  <body>
    <% if Rails.application.config.respond_to?(:mercury_config) %>
      <%= javascript_tag("jQuery.extend(Mercury.config, #{Rails.application.config.mercury_config});") %>
    <% end -%>

    <script type="text/javascript">
      var saveUrl = null;
      var options = {
        saveStyle: 'form',  // 'form', or 'json' (default json)
        saveMethod: 'PUT', // 'POST', or 'PUT', (create, vs. update -- default POST)
        visible: null     // if the interface should start visible or not (default true)
      };
      new Mercury.PageEditor(saveUrl, options);
    </script>
  </body>
</html>